import assert from "node:assert/strict";
import { writeFileSync } from "node:fs";

import { PDFDocument } from "pdf-lib";

import { buildPayrollPdf, type PayrollPdfEntry } from "../src/lib/payroll/pdf";

async function main() {
  const entries: PayrollPdfEntry[] = Array.from({ length: 19 }, (_, index) => ({
    employee_name_snapshot: `Empleado de Prueba ${index + 1}`,
    section_snapshot:
      index % 3 === 0 ? "BOTANICO FOH" : index % 3 === 1 ? "SELVA FOH" : "BOH",
    compensation_type_snapshot:
      index === 18 ? "fixed_weekly" : "hourly_training",
    regular_rate_snapshot: index === 18 ? null : 12.5,
    training_rate_snapshot: index === 18 ? null : 15,
    fixed_salary_snapshot: index === 18 ? 825 : null,
    regular_hours: index === 18 ? 0 : 40,
    training_hours: index % 4 === 0 ? 2 : 0,
    other_payments: index === 2 ? 75 : 0,
    comment:
      index === 2
        ? "Pago adicional autorizado para esta semana. Verificar antes de aprobar."
        : null,
  }));
  const bytes = await buildPayrollPdf({
    companyName: "Sibarita",
    weekStart: "2026-07-13",
    weekEnd: "2026-07-19",
    status: "submitted",
    submittedAt: "2026-07-13T12:33:04.758996+00:00",
    entries,
  });
  assert.equal(
    Buffer.from(bytes).subarray(0, 4).toString("ascii"),
    "%PDF",
    "generated bytes are a PDF",
  );
  const loaded = await PDFDocument.load(bytes);
  assert.equal(loaded.getTitle(), "Nomina Sibarita 2026-07-13");
  assert.equal(
    loaded.getPageCount(),
    2,
    "multi-page payroll and comments render predictably",
  );
  if (process.env.PAYROLL_PDF_OUTPUT) {
    writeFileSync(process.env.PAYROLL_PDF_OUTPUT, bytes);
  }
  console.log("Weekly payroll PDF generation and pagination tests passed.");
}

void main();
